module.exports = [
  {
    ignores: ["node_modules/", "assets/", "icons/", ".gitignore"],
  },
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        document: "readonly",
        window: "readonly",
        console: "readonly",
        localStorage: "readonly",
        indexedDB: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        Pardes: "writable",
        bgFilter: "readonly",
        setBodyBg: "readonly",
        BG_DB_NAME: "readonly",
        BG_DB_VERSION: "readonly",
        BG_DB_STORE: "readonly",
        BG_DB_KEY: "readonly",
        Promise: "readonly",
        prompt: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-var": "off",
      "prefer-const": "off",
      "vars-on-top": "off",
      "no-use-before-define": ["warn", { functions: false }],
      "no-unused-expressions": "off",
      "no-constant-binary-expression": "error",
      "no-self-compare": "warn",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable-loop": "warn",
    },
  },
];
